### ISSUE TITLE
review

### ISSUE THREAD

**Issue by HukakHePak** [volkovakaterin/abacus#1]
Привет, посмотрел задание

Если интересно, могу оставить фидбек по тестовому

**Comment by volkovakaterin** [comment]
> Привет, посмотрел задание
> 
> Если интересно, могу оставить фидбек по тестовому

Привет! Только сегодня увидела на почте твой комментарий. Если еще можно получить фидбэк, буду очень рада

**Comment by HukakHePak** [comment]
Нет проблем, раз уж предложил

По деплою:
\+ Забавно сделано растягивание при добавлении косточек
\+ Не дает ставить отрицательные числа
Просто и функционально, но немного неудобно, что поле ширины отскакивает вправо

По коду: 
\+ Дробление на компоненты 
\- Лучше группировать связанные компоненты. Bone положить в /BonesContainer, ManageColor ManageNumber в /Manage
\- Обычно папки и файлы компонентов именуются с большой буквы, как сам компонент. Так нагляднее
\+ Удивило использование стейт-менеджера
\+ Так вроде ничего в глаза не бросается, простая читаемая логика

**Comment by volkovakaterin** [comment]
> Нет проблем, раз уж предложил
> 
> По деплою: + Забавно сделано растягивание при добавлении косточек + Не дает ставить отрицательные числа Просто и функционально, но немного неудобно, что поле ширины отскакивает вправо
> 
> По коду: + Дробление на компоненты - Лучше группировать связанные компоненты. Bone положить в /BonesContainer, ManageColor ManageNumber в /Manage - Обычно папки и файлы компонентов именуются с большой буквы, как сам компонент. Так нагляднее + Удивило использование стейт-менеджера + Так вроде ничего в глаза не бросается, простая читаемая логика

Спасибо) А удивило использование стейт-менеджера, потому что через Сontext можно было сделать?
